### ISSUE TITLE
[URGENT] Milestone 3 pipeline error

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_group-314#51]
Make fails on eda_plots.py with error:

```
python src/eda_plots.py --filepath=data/cleaned-credit-default-data.csv --outdir=results
C:\Users\7ks42\Anaconda3\lib\site-packages\seaborn\axisgrid.py:230: UserWarning: The `size` paramter has been renamed to `height`; please update your code.
  warnings.warn(msg, UserWarning)
C:\Users\7ks42\Anaconda3\lib\site-packages\seaborn\axisgrid.py:715: UserWarning: Using the violinplot function without specifying `order` is likely to produce an incorrect plot.
  warnings.warn(warning)
python src/eda_plots.py --filepath=data/cleaned-credit-default-data.csv --outdir=results
C:\Users\7ks42\Anaconda3\lib\site-packages\seaborn\axisgrid.py:230: UserWarning: The `size` paramter has been renamed to `height`; please update your code.
  warnings.warn(msg, UserWarning)
C:\Users\7ks42\Anaconda3\lib\site-packages\seaborn\axisgrid.py:715: UserWarning: Using the violinplot function without specifying `order` is likely to produce an incorrect plot.
  warnings.warn(warning)
jupyter nbconvert --execute  doc/final_report.ipynb --to html_embed
Traceback (most recent call last):
  File "C:\Users\7ks42\Anaconda3\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\7ks42\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\7ks42\Anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\7ks42\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "C:\Users\7ks42\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 499, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "C:\Users\7ks42\Anaconda3\lib\site-packages\nbconvert\exporters\base.py", line 113, in get_exporter
    % (name, ', '.join(get_export_names())))
ValueError: Unknown exporter "html_embed", did you mean one of: asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?
make: *** [Makefile:25: doc/final_report.html] Error 1
```

**Comment by zoepan00** [comment]
Hi Kate, all of us test the make file and it worked ok last week. We only ran into this issue while ran it in the linux system and fixed it. Thanks

**Comment by ksedivyhaley** [comment]
Confirmed the issue is due to a configuration problem - no action needed.
